name: lint cdk

on: [push,pull_request]

jobs:
  node_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        working-directory: cdk
        with:
          node-version: 16
          cache: 'npm'
      - name: Install Node Dependencies
        run: npm ci
        working-directory: cdk
        env:
          CI: TRUE
      - name: Check Code format
        run: npm run format:check
        working-directory: cdk
      - name: Test Code Linting
        run: npm run lint
        working-directory: cdk
      - name: Save Code Linting Report JSON
        # npm script for ESLint
        #eslint --output-file eslint_report.json --format json .
        # See https://eslint.org/docs/user-guide/command-line-interface#options
        run: npm run lint:report
        working-directory: cdk
        # Continue to the next step even if this fails
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "cdk/eslint_report.json"
      - name: Upload ESLint report
        uses: actions/upload-artifact@v2
        with:
          name: eslint_report.json
          path: cdk/eslint_report.json
